### ISSUE TITLE
[EN] Feedback for: /showcase/case-study/chrome-dev-summit.html

### ISSUE THREAD

**Issue by oslego** [google/WebFundamentals#1225]
Contrast between text/links and background on the "Behind the scenes" section is very low.

![screen shot 2015-04-23 at 5 54 59 pm](https://cloud.githubusercontent.com/assets/63899/7302548/fcf3be30-e9e1-11e4-93a3-643d3f405531.jpg)

**Comment by PaulKinlan** [comment]
Hmm, this should have already been sorted. cc @pbakaus

**Comment by petele** [comment]
Believe this has been fixed.

**Comment by oslego** [comment]
No, this is not yet fixed.
See: https://developers.google.com/web/showcase/case-study/chrome-dev-summit

**Comment by pbakaus** [comment]
Good catch, will take a look.

**Comment by pbakaus** [comment]
Thanks much for the report, here's how it will look like once the new changes are deployed:
![screen shot 2015-06-16 at 14 30 57](https://cloud.githubusercontent.com/assets/43004/8182913/5641ee2c-1434-11e5-856f-1f78a4c9f32a.png)

**Comment by oslego** [comment]
Thanks for taking care of this!
