### ISSUE TITLE
Misspelled title on rel="noopener" page

### ISSUE THREAD

**Issue by DavidCzadilek** [google/WebFundamentals#4436]
https://developers.google.com/web/tools/lighthouse/audits/noopener

Misspelled title (devsite-product-description).
**rel="noopender"** instead of correct **rel="noopener"**
Probably dynamically created meta description and og:description are therefore misspelled as well.

**Comment by shaz13** [comment]
The page seems fine. I can't find it. A screenshot might be helpful if there is such typo

**Comment by DavidCzadilek** [comment]
Seems to have been fixed?
Havent found it in live source anymore, but in github search:
https://github.com/google/WebFundamentals/search?utf8=%E2%9C%93&q=noopender&type=

**Comment by BHSPitMonkey** [comment]
The misspelling still shows up in the `<meta name="description">` and `<meta property="og:description">` tags on that page (I just noticed it when sharing the link via a social platform which uses those tags to show a preview).
