### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by nazar-pc** [google/WebFundamentals#5780]
**Page Affected:** https://developers.google.com/web/updates/rss.xml

**What needs to be done?**
RSS should be valid XML document, otherwise Mozilla Thunderbird doesn't want to read it: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdevelopers.google.com%2Fweb%2Fupdates%2Frss.xml

This happened a while ago when you've silently changed URL and type of the feed from Atom to RSS.

**Comment by nazar-pc** [comment]
Looks like Atom feed is also back, but it is also broken in the same way

**Comment by petele** [comment]
There was an errant `FF` character in one of the files that broke the feed. I've checked the feed and removing that fixes most stuff. There are still some warnings, but the critical errors have been fixed.

If you still want the ATOM version, you can get it at https://developers.google.com/web/updates/atom.xml

**Comment by nazar-pc** [comment]
I still see `This feed does not validate.` for both feeds and Thunderbird still can't use it.

**Comment by nazar-pc** [comment]
I see that PR is not yet merged, will wait for it and check again

**Comment by petele** [comment]
Merged, and pushing live now, PR will get a comment when it's live on DevSite

**Comment by nazar-pc** [comment]
Works great, thanks!
