### ISSUE TITLE
Typo in “Introduction to variable fonts on the web”

### ISSUE THREAD

**Issue by simevidas** [google/WebFundamentals#5821]
URL: https://developers.google.com/web/fundamentals/design-and-ux/typography/variable-fonts/#fallbacks_and_browser_support

This line in the code example has a typo

```css
@supports (font-variations-setting: 'wdth' 200) {
```

It should be

```css
@supports (font-variation-settings: 'wdth' 200) {
```

**Comment by mustafa-x** [comment]
Thanks for this, looks like the typo has been fixed.

**Comment by simevidas** [comment]
@mustafa-x I’m still seeing it on the website. Does it take a while for the fix to be published?
